### ISSUE TITLE
Not downloading events anymore in UDM Pro since July

### ISSUE THREAD

**Issue by nijel** [danielfernau/unifi-protect-video-downloader#202]
It seems that somewhere around [Unifi Protect 2.0.0](https://community.ui.com/releases/UniFi-Protect-Application-2-0-0/d125d769-a514-4f02-b073-c4a2c2e72d23) the API has been changed. Unfortunately, I noticed this after months, so it's hard to tell exactly.

Following always returns no events:

https://github.com/danielfernau/unifi-protect-video-downloader/blob/a91db13ef4aed3356fac45900f00cccc5766ee94/protect_archiver/downloader/get_motion_event_list.py#L18-L21

When I change `type=motion` to `types=motion&types=smartDetectZone&types=smartDetectLine&types=ring&allCameras=true` I get what I want.

The `types` parameter is also accepted as comma separated list.

**Comment by danielfernau** [comment]
Hi @nijel - thanks for reporting this issue. I'll look into it as soon as possible and provide an update. Looks like they've added quite a few new types related to the smart detections which then are no longer tracked under the more general 'motion' type.

**Comment by rasander** [comment]
Hi Daniel.

Cool project, thank you for the work.

I just started today, and get same issue as this. No events downloaded. Can it be that the API got changed again? I'm using newest Unifi Protect (UniFi OS 3.1.9, Protect 2.8.28).

The download command work, however I only need the motion alerts to be downloaded.

Here is my log output
</snip>
$ poetry run protect-archiver events --address 10.160.1.22 --username LocalUser --password XXXX --start="2023-01-01 00:00:00" --end="2024-12-20 00:00:00" ~/unifi-protect-backupper/downloads/
Getting camera list
Successfully retrieved data from https://10.160.1.22:443/proxy/protect/api/cameras
Cameras found:
- CAM09 (646cae9102302503e40003fd)
- CAM01 (646cae9101de2503e40003f9)
- CAM14 (646cae9101742503e40003f5)
- CAM10 (646cae9101c72503e40003f8)
- CAM06 (646cae9101282503e40003f2)
- CAM05 (646cae91018e2503e40003f6)
- CAM08 (646cae91015b2503e40003f4)
- CAM07 (646cae91021e2503e40003fc)
- CAM02 (646cae91010e2503e40003f1)
- CAM15 (647f7f0100ecc803e402c551)
- CAM03 (646cae9101ab2503e40003f7)
- CAM16 (647f7d5d008fc803e402c483)
- CAM11 (646cae9100dd2503e40003f0)
- CAM12 (646cae9101432503e40003f3)
- CAM13 (646cae9101f62503e40003fa)
- CAM04 (646cae91020a2503e40003fb)
Getting motion event list
Successfully retrieved data from https://10.160.1.22:443/proxy/protect/api/events?types=ring,motion,smartDetectZone,smartDetectLine&start=1672531200000&end=1734652800000
Events found:

0 motion events found for all selected cameras between 2023-01-01 00:00:00 and 2024-12-20 00:00:00
Downloading motion event video files between 2023-01-01 00:00:00 and 2024-12-20 00:00:00 from 'https://10.160.1.22:443/proxy/protect/api/video/export'
0 files downloaded (0.0 b), 0 files skipped, 0 files failed, 0 files total
</snip>

Thank you in advance.
