### ISSUE TITLE
Add option to select between local time and GMT in file name timestamps

### ISSUE THREAD

**Issue by danielfernau** [danielfernau/unifi-protect-video-downloader#30]
As suggested by @tauren in https://github.com/unifi-toolbox/unifi-protect-video-downloader/issues/29#issuecomment-638760817

**Comment by hakarune** [comment]
How can it be set?

**Comment by danielfernau** [comment]
This option is not yet implemented. It will be a command line flag to toggle between the two options. Probably something like `--filename-timestamp-utc` to use UTC/GMT, and default to local time zone if omitted.

The file name generators are hard-coded at the moment:
- https://github.com/danielfernau/unifi-protect-video-downloader/blob/068d3d6377e485e21b9c30f791cf8f83c8afe778/protect_archiver/downloader/download_footage.py#L55
- https://github.com/danielfernau/unifi-protect-video-downloader/blob/068d3d6377e485e21b9c30f791cf8f83c8afe778/protect_archiver/downloader/download_motion_event.py#L40
- https://github.com/danielfernau/unifi-protect-video-downloader/blob/068d3d6377e485e21b9c30f791cf8f83c8afe778/protect_archiver/downloader/download_snapshot.py#L34

**Comment by hakarune** [comment]
Oh okay. So upcoming release then?
