### ISSUE TITLE
Allow environment variables to be used for username and password, maybe all flags

### ISSUE THREAD

**Issue by scelfo** [danielfernau/unifi-protect-video-downloader#385]
This is a small nitpick suggestion. When username and password are specified on the command line those values are visible when running simple commands like 'ps'.

This project is already using docker so it would be nice to follow a common docker pattern and allow configuration via environment variables.

**Comment by danielfernau** [comment]
Hi @scelfo and thanks for the suggestion. I'll look into it and let you know once the feature is available. Definitely makes a lot of sense. 👍

**Comment by danielfernau** [comment]
Hi @scelfo - the feature is now available for the Docker image tag `edge` and will be part of the upcoming v2.3.0 release.
Have a look at https://github.com/danielfernau/unifi-protect-video-downloader/pull/409#issue-2128253573 or use `--help` in the CLI for a full list of supported environment variables.
Thanks again for the suggestion and enjoy!
