### ISSUE TITLE
Motion event list seems not to be working

### ISSUE THREAD

**Issue by fotoshare** [danielfernau/unifi-protect-video-downloader#398]
Getting motion event list
Successfully retrieved data from https://x.x.x.x:443/proxy/protect/api/events?types=ring,motion,smartDetectZone,smartDetectLine&start=1703458800000&end=1703545200000
Events found:

0 motion events found for all selected cameras between 2023-12-25 00:00:00 and 2023-12-26 00:00:00
Downloading motion event video files between 2023-12-25 00:00:00 and 2023-12-26 00:00:00 from 'https://x.x.x.x:443/proxy/protect/api/video/export'
0 files downloaded (0.0 b), 0 files skipped, 0 files failed, 0 files total

So I tried to paste "https://x.x.x.x:443/proxy/protect/api/events?types=ring,motion,smartDetectZone,smartDetectLine&start=1703458800000&end=1703545200000" into chrome. 
Result []

When I tried "https://x.x.x.x:443/proxy/protect/api/events?types=motion&start=1703458800000&end=1703545200000" I get loads of results.

Does this help to find out what the problem could be?

**Comment by danielfernau** [comment]
Thanks for reporting, I'll look into this and check what's changed on the Protect API side.

**Comment by danielfernau** [comment]
Related to #388, which contains a solution for this issue :)

**Comment by L3o-pold** [comment]
@danielfernau please release a new version to avoid using edge docker image 🙏

**Comment by danielfernau** [comment]
@L3o-pold done, sorry for the delay and thanks for the reminder! 👍 

Release: https://github.com/danielfernau/unifi-protect-video-downloader/releases/tag/v2.3.0
Docker image: `unifitoolbox/protect-archiver:2.3.0`
