### ISSUE TITLE
Unnecessary empty files

### ISSUE THREAD

**Issue by purpleidea** [danielfernau/unifi-protect-video-downloader#6]
Running this command:

```
python3 ~/code/src/unifi-protect-video-downloader/main.py --address=xxx.xxx.xxx.xxx --username="*****" --password="*****" --cameras="all" --start="2019-01-01 00:00:00-0500" --end="2021-01-01 00:00:00-0500" --dest=./videos --skip-existing-files --use-subfolders --ignore-failed-downloads
```

Produces many empty files. Eg:

```
$ tree
    ├── 13
    │   └── cam0_03fa
    │       ├── cam0_03fa_2019-12-13--00-00-00-0500_2019-12-13--00-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--01-00-00-0500_2019-12-13--01-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--02-00-00-0500_2019-12-13--02-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--03-00-00-0500_2019-12-13--03-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--04-00-00-0500_2019-12-13--04-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--05-00-00-0500_2019-12-13--05-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--06-00-00-0500_2019-12-13--06-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--07-00-00-0500_2019-12-13--07-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--08-00-00-0500_2019-12-13--08-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--09-00-00-0500_2019-12-13--09-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--10-00-00-0500_2019-12-13--10-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--11-00-00-0500_2019-12-13--11-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--12-00-00-0500_2019-12-13--12-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--13-00-00-0500_2019-12-13--13-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--14-00-00-0500_2019-12-13--14-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--15-00-00-0500_2019-12-13--15-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--16-00-00-0500_2019-12-13--16-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--17-00-00-0500_2019-12-13--17-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--18-00-00-0500_2019-12-13--18-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--19-00-00-0500_2019-12-13--19-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--20-00-00-0500_2019-12-13--20-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--21-00-00-0500_2019-12-13--21-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-13--22-00-00-0500_2019-12-13--22-59-59-0500.mp4
    │       └── cam0_03fa_2019-12-13--23-00-00-0500_2019-12-13--23-59-59-0500.mp4
    ├── 14
    │   └── cam0_03fa
    │       ├── cam0_03fa_2019-12-14--00-00-00-0500_2019-12-14--00-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-14--01-00-00-0500_2019-12-14--01-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-14--02-00-00-0500_2019-12-14--02-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-14--03-00-00-0500_2019-12-14--03-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-14--04-00-00-0500_2019-12-14--04-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-14--05-00-00-0500_2019-12-14--05-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-14--06-00-00-0500_2019-12-14--06-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-14--07-00-00-0500_2019-12-14--07-59-59-0500.mp4
    │       ├── cam0_03fa_2019-12-14--08-00-00-0500_2019-12-14--08-59-59-0500.mp4

```

And so on. It would be excellent to avoid creating these.

Thanks!

---
**Edit:** removed IP address and username/password from provided command example

**Comment by purpleidea** [comment]
NOTE: If you specify a time range earlier than when you ever had recordings, you get empty dirs getting created with no video files inside. (just the cam0... dir)

**Comment by danielfernau** [comment]
The API currently does not return a 'no recordings for requested time range' error of any kind and instead provides a *.mp4 file like it also does for every "valid" time range. 

So for now there's only the option to (automatically) delete these files based on their file size after they have been downloaded. Have a look at https://superuser.com/a/644274 for more information on how to do that. Easiest way would be to create a bash script that runs the downloader followed by the `find` command as explained in the linked article.

Hope this helps!

**Comment by purpleidea** [comment]
I can bash script, but it might be nice to do this natively, even if it's a hack and we check for size == 0.
I don't like writing python anymore, so this is untested, but here's the general idea:

https://github.com/danielfernau/unifi-protect-video-downloader/pull/7

LMK

**Comment by danielfernau** [comment]
Agreed. Checking if it's empty before starting the download only works if the file is "finalized" on the UniFi Protect side before downloading, which it is not. Instead of exporting it to a file on the CloudKey and then providing the download link (including the HTTP `Content-Length` header etc.) the UniFi Protect API currently returns a download stream of unknown size (due to missing length header). Therefore, the next best way to remove the empty files would be to have the file write stream function finish, then check the file size and remove it if its size is zero. I'll do a few experiments and see what works best...
